// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSjW2JNnT-fFUIxyEJjRENmK8uAomySDA',
    appId: '1:568808621496:android:admin1234567890abcd',
    messagingSenderId: '568808621496',
    projectId: 'food-delivery-app-7752',
    databaseURL: 'https://food-delivery-app-7752.firebaseio.com',
    storageBucket: 'food-delivery-app-7752.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSjW2JNnT-fFUIxyEJjRENmK8uAomySDA',
    appId: '1:568808621496:ios:ca85486bc028509ea',
    messagingSenderId: '568808621496',
    projectId: 'food-delivery-app-7752',
    databaseURL: 'https://food-delivery-app-7752.firebaseio.com',
    storageBucket: 'food-delivery-app-7752.firebasestorage.app',
    iosBundleId: 'com.admin_app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSjW2JNnT-fFUIxyEJjRENmK8uAomySDA',
    appId: '1:568808621496:web:ca85486bc028509eafc529',
    messagingSenderId: '568808621496',
    projectId: 'food-delivery-app-7752',
    databaseURL: 'https://food-delivery-app-7752.firebaseio.com',
    storageBucket: 'food-delivery-app-7752.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSjW2JNnT-fFUIxyEJjRENmK8uAomySDA',
    appId: '1:568808621496:macos:ca85486bc028509ea',
    messagingSenderId: '568808621496',
    projectId: 'food-delivery-app-7752',
    databaseURL: 'https://food-delivery-app-7752.firebaseio.com',
    storageBucket: 'food-delivery-app-7752.firebasestorage.app',
    iosBundleId: 'com.admin_app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSjW2JNnT-fFUIxyEJjRENmK8uAomySDA',
    appId: '1:568808621496:windows:ca85486bc028509ea',
    messagingSenderId: '568808621496',
    projectId: 'food-delivery-app-7752',
    databaseURL: 'https://food-delivery-app-7752.firebaseio.com',
    storageBucket: 'food-delivery-app-7752.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCSjW2JNnT-fFUIxyEJjRENmK8uAomySDA',
    appId: '1:568808621496:linux:ca85486bc028509ea',
    messagingSenderId: '568808621496',
    projectId: 'food-delivery-app-7752',
    databaseURL: 'https://food-delivery-app-7752.firebaseio.com',
    storageBucket: 'food-delivery-app-7752.firebasestorage.app',
  );
}
